CREATE DATABASE IF NOT EXISTS smakkita CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE smakkita;
CREATE TABLE users (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(150) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role ENUM('student','admin') NOT NULL DEFAULT 'student', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE students (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NOT NULL UNIQUE, birth_date DATE NULL, age TINYINT UNSIGNED NULL, domicile VARCHAR(80) NULL, previous_school VARCHAR(180) NULL, education_preference ENUM('sma','smk','undecided') NOT NULL DEFAULT 'undecided', percentile DECIMAL(5,2) NOT NULL DEFAULT 100, admission_path VARCHAR(40) NULL, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE quiz_questions (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, question VARCHAR(255) NOT NULL, indicator VARCHAR(60) NOT NULL, weight DECIMAL(6,3) NOT NULL DEFAULT 1, order_number INT NOT NULL, is_active TINYINT(1) NOT NULL DEFAULT 1);
CREATE TABLE quiz_answers (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, student_id INT UNSIGNED NOT NULL, question_id INT UNSIGNED NOT NULL, answer TINYINT UNSIGNED NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_answer(student_id,question_id), FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE, FOREIGN KEY(question_id) REFERENCES quiz_questions(id) ON DELETE CASCADE);
CREATE TABLE interest_scores (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, student_id INT UNSIGNED NOT NULL, indicator VARCHAR(60) NOT NULL, score DECIMAL(5,2) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
CREATE TABLE academic_scores (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, student_id INT UNSIGNED NOT NULL UNIQUE, science DECIMAL(5,2) NOT NULL, social_studies DECIMAL(5,2) NOT NULL, indonesian DECIMAL(5,2) NOT NULL, english DECIMAL(5,2) NOT NULL, mathematics DECIMAL(5,2) NOT NULL, civics DECIMAL(5,2) NOT NULL, academic_average DECIMAL(5,2) NOT NULL, FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
CREATE TABLE academic_achievements (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, student_id INT UNSIGNED NOT NULL, level_name VARCHAR(30) NOT NULL, organization_type VARCHAR(30) NOT NULL, is_tiered TINYINT(1) NOT NULL DEFAULT 0, rank_number TINYINT UNSIGNED NOT NULL DEFAULT 1, score DECIMAL(5,2) NOT NULL, FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
CREATE TABLE non_academic_achievements LIKE academic_achievements;
CREATE TABLE organization_scores (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, student_id INT UNSIGNED NOT NULL UNIQUE, role_name VARCHAR(30) NOT NULL, score DECIMAL(5,2) NOT NULL, FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
CREATE TABLE school_data (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, npsn VARCHAR(30) NOT NULL UNIQUE, name VARCHAR(180) NOT NULL, address TEXT NOT NULL, domicile VARCHAR(80) NOT NULL, school_type ENUM('SMA','SMK') NOT NULL, average_score DECIMAL(5,2) NULL, capacity INT UNSIGNED NULL, capacity_prestasi_akademik INT UNSIGNED NULL, capacity_prestasi_nonakademik INT UNSIGNED NULL, capacity_tahap_kedua INT UNSIGNED NULL, capacity_afirmasi INT UNSIGNED NULL, capacity_zonasi INT UNSIGNED NULL, accreditation VARCHAR(20) NULL, admission_prestasi_akademik DECIMAL(5,2) NULL, admission_prestasi_nonakademik DECIMAL(5,2) NULL, admission_tahap_kedua DECIMAL(5,2) NULL, admission_afirmasi DECIMAL(5,2) NULL, admission_zonasi DECIMAL(5,2) NULL, source_file VARCHAR(255) NOT NULL, is_active TINYINT(1) DEFAULT 1, INDEX idx_school_type(school_type), INDEX idx_domicile(domicile));
CREATE TABLE school_competencies (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, school_id BIGINT UNSIGNED NOT NULL, competency VARCHAR(180) NOT NULL, FOREIGN KEY(school_id) REFERENCES school_data(id) ON DELETE CASCADE);
CREATE TABLE majors (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(150) NOT NULL UNIQUE, explanation TEXT, priority INT DEFAULT 0, is_active TINYINT(1) DEFAULT 1);
CREATE TABLE major_aliases (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, major_id INT UNSIGNED NOT NULL, alias_name VARCHAR(150) NOT NULL, UNIQUE KEY uq_alias(major_id,alias_name), FOREIGN KEY(major_id) REFERENCES majors(id) ON DELETE CASCADE);
CREATE TABLE recommendations (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, student_id INT UNSIGNED NOT NULL, model_version VARCHAR(50) NULL, predicted_interest VARCHAR(80) NULL, confidence DECIMAL(6,4) NULL, student_score DECIMAL(6,2) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(student_id) REFERENCES students(id) ON DELETE CASCADE);
CREATE TABLE recommendation_details (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, recommendation_id BIGINT UNSIGNED NOT NULL, school_id BIGINT UNSIGNED NOT NULL, rank_number INT NOT NULL, score DECIMAL(6,2) NOT NULL, explanation JSON NULL, FOREIGN KEY(recommendation_id) REFERENCES recommendations(id) ON DELETE CASCADE, FOREIGN KEY(school_id) REFERENCES school_data(id));
CREATE TABLE datasets (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, file_type VARCHAR(10) NOT NULL, source_path VARCHAR(500) NOT NULL, row_count INT DEFAULT 0, status VARCHAR(30) DEFAULT 'uploaded', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE dataset_versions (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, dataset_id INT UNSIGNED NOT NULL, version_name VARCHAR(50) NOT NULL, is_active TINYINT(1) DEFAULT 0, FOREIGN KEY(dataset_id) REFERENCES datasets(id) ON DELETE CASCADE);
CREATE TABLE ml_models (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, version_name VARCHAR(50) NOT NULL UNIQUE, model_type VARCHAR(80) NOT NULL, dataset_version_id INT UNSIGNED NULL, target_name VARCHAR(100) NOT NULL, features JSON NOT NULL, metrics JSON NULL, model_path VARCHAR(500) NOT NULL, status ENUM('active','archived') DEFAULT 'archived', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(dataset_version_id) REFERENCES dataset_versions(id));
CREATE TABLE training_runs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, ml_model_id INT UNSIGNED NULL, train_count INT NOT NULL, test_count INT NOT NULL, metrics JSON NULL, started_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(ml_model_id) REFERENCES ml_models(id));
CREATE TABLE system_settings (setting_key VARCHAR(100) PRIMARY KEY, setting_value VARCHAR(255) NOT NULL);
CREATE TABLE audit_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id INT UNSIGNED NULL, action_name VARCHAR(100) NOT NULL, detail JSON NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL);

USE sma_kita;
CREATE TABLE IF NOT EXISTS passion_professions (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 profession VARCHAR(180) NOT NULL UNIQUE,
 indicator VARCHAR(60) NOT NULL,
 description VARCHAR(255) NULL,
 is_active TINYINT(1) NOT NULL DEFAULT 1,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO passion_professions(profession,indicator,description) VALUES('Actor / Actress','Linguistic','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Actuary','Logical - Mathematical','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Anthropologist','Spatial-Visualization','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Archeologist','Naturalist','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Artist','Musical','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Astronomer','Naturalist','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Athlete','Intrapersonal','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Audiologist','Logical - Mathematical','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Broadcaster','Linguistic','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Business Analyst','Interpersonal','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Business manager','Logical - Mathematical','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Chief financial officer','Interpersonal','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Computer programmer','Linguistic','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Dancer','Musical','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Editor','Logical - Mathematical','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Engineer','Spatial-Visualization','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Geologist','Naturalist','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Graphic Designer','Spatial-Visualization','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Historian','Intrapersonal','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Interior Decorator','Interpersonal','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Internal auditor','Intrapersonal','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Journalist','Linguistic','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Lawyer','Logical - Mathematical','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Leader','Intrapersonal','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Manager','Logical - Mathematical','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Marine Biologist','Logical - Mathematical','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Marketing','Linguistic','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Mathematician','Spatial-Visualization','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Mechanic','Bodily','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Medical','Interpersonal','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Militry','Interpersonal','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Music teacher','Interpersonal','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Nature photographer','Naturalist','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Para Medical (physiotherapy, occupational theropy, audio and speech language theropy, nursing)','Interpersonal','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Para Militry (https://en.wikipedia.org/wiki/Paramilitary_forces_of_India)','Bodily','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Pharmacist','Interpersonal','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Physical Therapist','Naturalist','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Physician','Interpersonal','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Physicist','Logical - Mathematical','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Pilot','Naturalist','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Poet','Musical','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Police Force (Spies, CBI officials, CID, Detectives)','Interpersonal','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Politician','Logical - Mathematical','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Pre Primary Teacher (2020 NEP and Mental Health)','Bodily','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Primary Teacher','Musical','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Psychologist','Logical - Mathematical','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Receptionist','Interpersonal','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Recording engineer','Interpersonal','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Research analyst','Linguistic','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Sales Representative','Logical - Mathematical','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Social Worker','Bodily','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Sound editor','Naturalist','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Stock Broker','Intrapersonal','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Veterinarian','Intrapersonal','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
INSERT INTO passion_professions(profession,indicator,description) VALUES('Writer','Linguistic','Profesi yang muncul pada Dataset Project 404') ON DUPLICATE KEY UPDATE indicator=VALUES(indicator),is_active=1;
