USE smakkita;

UPDATE quiz_questions
SET question = CASE order_number
    WHEN 1 THEN 'Saya senang menjelaskan ide dengan kata-kata.'
    WHEN 2 THEN 'Saya cepat menangkap irama dan melodi.'
    WHEN 3 THEN 'Saya belajar dengan baik melalui aktivitas fisik.'
    WHEN 4 THEN 'Saya menyukai pola, angka, dan teka-teki.'
    WHEN 5 THEN 'Saya suka menggambar, membaca peta, dan membuat desain visual.'
    WHEN 6 THEN 'Saya merasa bersemangat saat bekerja bersama orang lain.'
    WHEN 7 THEN 'Saya sering merenungkan pikiran dan perasaan saya sendiri.'
    WHEN 8 THEN 'Saya ingin tahu tentang tumbuhan, hewan, dan alam.'
    WHEN 9 THEN 'Saya suka meneliti mengapa sesuatu bisa terjadi.'
    WHEN 10 THEN 'Saya senang menguji gagasan berdasarkan bukti.'
    WHEN 11 THEN 'Saya suka membuat solusi secara bertahap dan teratur.'
    WHEN 12 THEN 'Saya senang mengelompokkan informasi berdasarkan pola.'
    WHEN 13 THEN 'Saya memperhatikan warna, bentuk, dan detail tata letak.'
    WHEN 14 THEN 'Saya senang membuat poster, video, atau cerita visual.'
    WHEN 15 THEN 'Saya dapat membayangkan bagaimana benda-benda saling tersusun.'
    WHEN 16 THEN 'Saya suka memperbaiki tampilan sebuah desain.'
    WHEN 17 THEN 'Saya senang menulis cerita atau penjelasan.'
    WHEN 18 THEN 'Saya dapat meyakinkan orang lain dengan alasan yang jelas.'
    WHEN 19 THEN 'Saya suka mempelajari kata-kata dan bahasa baru.'
    WHEN 20 THEN 'Saya senang menyampaikan ide kepada orang lain.'
    WHEN 21 THEN 'Saya dapat mengarahkan orang lain untuk mencapai tujuan.'
    WHEN 22 THEN 'Saya senang mendengarkan dan membantu orang lain.'
    WHEN 23 THEN 'Saya dapat bekerja dengan baik dalam kegiatan kelompok.'
    WHEN 24 THEN 'Saya tertarik pada pemasaran atau cara memahami orang lain.'
    WHEN 25 THEN 'Saya dapat mengenali melodi dan pola musik.'
    WHEN 26 THEN 'Saya senang membuat atau menyusun bunyi dan musik.'
    WHEN 27 THEN 'Musik membantu saya menyampaikan ide atau perasaan.'
    WHEN 28 THEN 'Saya memperhatikan irama dalam kegiatan sehari-hari.'
    WHEN 29 THEN 'Saya paling mudah belajar dengan melakukan dan berlatih secara langsung.'
    WHEN 30 THEN 'Saya senang membuat, memperbaiki, atau merakit sesuatu.'
    WHEN 31 THEN 'Saya memiliki koordinasi gerak yang baik dalam kegiatan fisik.'
    WHEN 32 THEN 'Saya lebih menyukai proyek praktik daripada hanya membaca petunjuk.'
    WHEN 33 THEN 'Saya rutin merenungkan kelebihan dan kekurangan diri sendiri.'
    WHEN 34 THEN 'Saya menetapkan tujuan pribadi dan memantau kemajuannya.'
    WHEN 35 THEN 'Saya dapat bekerja mandiri dalam waktu yang lama.'
    WHEN 36 THEN 'Saya senang melakukan kegiatan tenang untuk lebih memahami diri sendiri.'
    WHEN 37 THEN 'Saya senang mengamati tumbuhan, hewan, atau ekosistem.'
    WHEN 38 THEN 'Saya peduli terhadap masalah lingkungan.'
    WHEN 39 THEN 'Saya suka mengelompokkan atau membandingkan berbagai hal di alam.'
    WHEN 40 THEN 'Saya ingin tahu tentang makanan, pertanian, atau keberlanjutan.'
    ELSE question
END
WHERE order_number BETWEEN 1 AND 40;
