USE smakkita;
INSERT INTO quiz_questions(question,indicator,weight,order_number) VALUES
('I like researching why things happen.','Logical-Mathematical',1,9),('I enjoy testing ideas with evidence.','Logical-Mathematical',1,10),('I like building step-by-step solutions.','Logical-Mathematical',1,11),('I enjoy organizing information into patterns.','Logical-Mathematical',1,12),
('I notice colors, shapes, and layout details.','Spatial-Visualization',1,13),('I enjoy creating posters, videos, or visual stories.','Spatial-Visualization',1,14),('I can imagine how objects fit together.','Spatial-Visualization',1,15),('I like improving the appearance of a design.','Spatial-Visualization',1,16),
('I enjoy writing stories or explanations.','Linguistic',1,17),('I can persuade people with clear reasons.','Linguistic',1,18),('I like learning new words and languages.','Linguistic',1,19),('I enjoy presenting ideas to an audience.','Linguistic',1,20),
('I naturally coordinate people toward a goal.','Interpersonal',1,21),('I enjoy listening to and helping others.','Interpersonal',1,22),('I work well in group projects.','Interpersonal',1,23),('I am interested in marketing or understanding audiences.','Interpersonal',1,24),
('I can recognize melodies and musical patterns.','Musical',1,25),('I enjoy making or arranging sounds.','Musical',1,26),('Music helps me express ideas or emotions.','Musical',1,27),('I pay attention to rhythm in everyday activities.','Musical',1,28),
('I learn best by doing and practicing physically.','Bodily',1,29),('I enjoy making, repairing, or assembling things.','Bodily',1,30),('I have good coordination in movement-based activities.','Bodily',1,31),('I prefer practical projects to only reading instructions.','Bodily',1,32),
('I regularly reflect on my strengths and weaknesses.','Intrapersonal',1,33),('I set personal goals and track my progress.','Intrapersonal',1,34),('I can work independently for a long time.','Intrapersonal',1,35),('I enjoy quiet activities that help me understand myself.','Intrapersonal',1,36),
('I enjoy observing plants, animals, or ecosystems.','Naturalist',1,37),('I care about environmental problems.','Naturalist',1,38),('I like classifying or comparing things in nature.','Naturalist',1,39),('I am curious about food, farming, or sustainability.','Naturalist',1,40);

UPDATE quiz_questions SET question = CASE order_number
WHEN 9 THEN 'Saya suka meneliti mengapa sesuatu bisa terjadi.' WHEN 10 THEN 'Saya senang menguji gagasan berdasarkan bukti.' WHEN 11 THEN 'Saya suka membuat solusi secara bertahap dan teratur.' WHEN 12 THEN 'Saya senang mengelompokkan informasi berdasarkan pola.' WHEN 13 THEN 'Saya memperhatikan warna, bentuk, dan detail tata letak.' WHEN 14 THEN 'Saya senang membuat poster, video, atau cerita visual.' WHEN 15 THEN 'Saya dapat membayangkan bagaimana benda-benda saling tersusun.' WHEN 16 THEN 'Saya suka memperbaiki tampilan sebuah desain.'
WHEN 17 THEN 'Saya senang menulis cerita atau penjelasan.' WHEN 18 THEN 'Saya dapat meyakinkan orang lain dengan alasan yang jelas.' WHEN 19 THEN 'Saya suka mempelajari kata-kata dan bahasa baru.' WHEN 20 THEN 'Saya senang menyampaikan ide kepada orang lain.' WHEN 21 THEN 'Saya dapat mengarahkan orang lain untuk mencapai tujuan.' WHEN 22 THEN 'Saya senang mendengarkan dan membantu orang lain.' WHEN 23 THEN 'Saya dapat bekerja dengan baik dalam kegiatan kelompok.' WHEN 24 THEN 'Saya tertarik pada pemasaran atau cara memahami orang lain.'
WHEN 25 THEN 'Saya dapat mengenali melodi dan pola musik.' WHEN 26 THEN 'Saya senang membuat atau menyusun bunyi dan musik.' WHEN 27 THEN 'Musik membantu saya menyampaikan ide atau perasaan.' WHEN 28 THEN 'Saya memperhatikan irama dalam kegiatan sehari-hari.' WHEN 29 THEN 'Saya paling mudah belajar dengan melakukan dan berlatih secara langsung.' WHEN 30 THEN 'Saya senang membuat, memperbaiki, atau merakit sesuatu.' WHEN 31 THEN 'Saya memiliki koordinasi gerak yang baik dalam kegiatan fisik.' WHEN 32 THEN 'Saya lebih menyukai proyek praktik daripada hanya membaca petunjuk.'
WHEN 33 THEN 'Saya rutin merenungkan kelebihan dan kekurangan diri sendiri.' WHEN 34 THEN 'Saya menetapkan tujuan pribadi dan memantau kemajuannya.' WHEN 35 THEN 'Saya dapat bekerja mandiri dalam waktu yang lama.' WHEN 36 THEN 'Saya senang melakukan kegiatan tenang untuk lebih memahami diri sendiri.' WHEN 37 THEN 'Saya senang mengamati tumbuhan, hewan, atau ekosistem.' WHEN 38 THEN 'Saya peduli terhadap masalah lingkungan.' WHEN 39 THEN 'Saya suka mengelompokkan atau membandingkan berbagai hal di alam.' WHEN 40 THEN 'Saya ingin tahu tentang makanan, pertanian, atau keberlanjutan.'
ELSE question END WHERE order_number BETWEEN 9 AND 40;
