<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/database.php'; require_once __DIR__ . '/../recommendation/Scoring.php'; require_login();
$user = current_user(); $stmt = db()->prepare('SELECT id FROM students WHERE user_id = ?'); $stmt->execute([$user['id']]); $student = $stmt->fetch(); if (!$student) redirect('student/profile.php');
$error = '';
$levels = ['none'=>'Tidak ada','international'=>'Internasional','national'=>'Nasional','province'=>'Provinsi','city'=>'Kota/Kabupaten'];
function achievementInput(string $prefix): array { return [$_POST[$prefix . '_level'] ?? 'none', $_POST[$prefix . '_organization'] ?? 'government', isset($_POST[$prefix . '_tiered']), (int)($_POST[$prefix . '_rank'] ?? 1)]; }
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!verify_csrf($_POST['csrf'] ?? null)) $error = 'Invalid form token.';
    else { $pdo = db(); $pdo->beginTransaction(); try { [$academicLevel,$academicOrganization,$academicTiered,$academicRank] = achievementInput('academic'); [$nonLevel,$nonOrganization,$nonTiered,$nonRank] = achievementInput('non'); $pdo->prepare('DELETE FROM academic_achievements WHERE student_id = ?')->execute([$student['id']]); $pdo->prepare('DELETE FROM non_academic_achievements WHERE student_id = ?')->execute([$student['id']]); $saveAcademic = $pdo->prepare('INSERT INTO academic_achievements(student_id,level_name,organization_type,is_tiered,rank_number,score) VALUES(?,?,?,?,?,?)'); $saveNon = $pdo->prepare('INSERT INTO non_academic_achievements(student_id,level_name,organization_type,is_tiered,rank_number,score) VALUES(?,?,?,?,?,?)'); $saveAcademic->execute([$student['id'],$academicLevel,$academicOrganization,$academicTiered?1:0,$academicRank,achievementScore($academicLevel,$academicOrganization,$academicTiered,$academicRank)]); $saveNon->execute([$student['id'],$nonLevel,$nonOrganization,$nonTiered?1:0,$nonRank,achievementScore($nonLevel,$nonOrganization,$nonTiered,$nonRank)]); $pdo->commit(); redirect('dashboard.php'); } catch (Throwable $exception) { $pdo->rollBack(); $error = 'Achievement data could not be saved.'; } }
}
 $title = 'Prestasi'; require __DIR__ . '/../includes/header.php';
?><div class="container py-5"><div class="row justify-content-center"><div class="col-lg-9"><div class="eyebrow mb-2">Prestasi</div><h1 class="section-title mb-3">Tambahkan pencapaianmu.</h1><p class="text-muted">Prestasi akademik dan non-akademik dinilai serta disimpan secara terpisah.</p><?php if ($error): ?><div class="alert alert-danger"><?= e($error) ?></div><?php endif; ?><form method="post"><input type="hidden" name="csrf" value="<?= e(csrf_token()) ?>"><div class="row g-4"><?php foreach (['academic'=>'Prestasi akademik','non'=>'Prestasi non-akademik'] as $prefix=>$heading): ?><div class="col-lg-6"><div class="panel"><h4><?= e($heading) ?></h4><label class="form-label mt-3">Tingkat</label><select name="<?= $prefix ?>_level" class="form-select mb-3"><?php foreach ($levels as $value=>$label): ?><option value="<?= e($value) ?>"><?= e($label) ?></option><?php endforeach; ?></select><label class="form-label">Jenis penyelenggara</label><select name="<?= $prefix ?>_organization" class="form-select mb-3"><option value="government">Pemerintah / Resmi</option><option value="parent">Induk organisasi / Resmi</option><option value="other">Kurasi / Pameran / Festival</option></select><label class="form-label">Peringkat</label><select name="<?= $prefix ?>_rank" class="form-select mb-3"><option value="1">Juara 1</option><option value="2">Juara 2</option><option value="3">Juara 3</option></select><div class="form-check"><input class="form-check-input" type="checkbox" name="<?= $prefix ?>_tiered" id="<?= $prefix ?>_tiered"><label class="form-check-label" for="<?= $prefix ?>_tiered">Kompetisi bertingkat</label></div></div></div><?php endforeach; ?></div><button class="btn btn-accent rounded-pill px-4 mt-4">Simpan prestasi <i class="bi bi-arrow-right"></i></button></form></div></div></div><?php require __DIR__ . '/../includes/footer.php'; ?>