<?php
declare(strict_types=1);
require_once __DIR__.'/../config/database.php';
require_once __DIR__.'/../recommendation/Scoring.php';
require_once __DIR__.'/../recommendation/RecommendationEngine.php';
require_once __DIR__.'/../recommendation/MajorRecommendation.php';
require_once __DIR__.'/../ml/Predictor.php';
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');
require_login();
$user=current_user();
$stmt=db()->prepare('SELECT s.*,a.academic_average,a.science,a.social_studies,a.indonesian,a.english,a.mathematics,a.civics FROM students s LEFT JOIN academic_scores a ON a.student_id=s.id WHERE s.user_id=?');$stmt->execute([$user['id']]);$student=$stmt->fetch()?:[];if(empty($student['id']))redirect('student/profile.php');
$completion=db()->prepare('SELECT a.id academic_id,aa.id academic_achievement_id,na.id non_academic_achievement_id,o.id organization_id FROM students s LEFT JOIN academic_scores a ON a.student_id=s.id LEFT JOIN academic_achievements aa ON aa.student_id=s.id LEFT JOIN non_academic_achievements na ON na.student_id=s.id LEFT JOIN organization_scores o ON o.student_id=s.id WHERE s.id=?');$completion->execute([(int)$student['id']]);$state=$completion->fetch();
if(!$state['academic_id'])redirect('student/academic.php');if(!$state['academic_achievement_id']||!$state['non_academic_achievement_id'])redirect('student/achievements.php');if(!$state['organization_id'])redirect('student/organization.php');
$studentId=(int)$student['id'];
$q=db()->prepare('SELECT COALESCE(MAX(score),0) FROM academic_achievements WHERE student_id=?');$q->execute([$studentId]);$academicAchievement=(float)$q->fetchColumn();
$q=db()->prepare('SELECT COALESCE(MAX(score),0) FROM non_academic_achievements WHERE student_id=?');$q->execute([$studentId]);$nonAcademicAchievement=(float)$q->fetchColumn();
$q=db()->prepare('SELECT COALESCE(score,0) FROM organization_scores WHERE student_id=?');$q->execute([$studentId]);$organization=(float)$q->fetchColumn();
$path=normalizeAdmissionPath((string)($student['admission_path']??''));if($path==='')redirect('student/profile.php');
$routeLabels=['prestasi_akademik_sma'=>'Prestasi Akademik','prestasi_akademik_smk'=>'Prestasi Akademik','prestasi_non_akademik'=>'Prestasi Non-Akademik','afirmasi_sma'=>'Afirmasi','zonasi_sma'=>'Zonasi','tahap_kedua_sma'=>'Tahap Kedua','afirmasi_tahap_kedua_smk'=>'Afirmasi & Tahap Kedua'];$routeLabel=$routeLabels[$path]??ucwords(str_replace('_',' ',$path));
$subjects=array_filter([(float)($student['indonesian']??0),(float)($student['civics']??0),(float)($student['social_studies']??0),(float)($student['mathematics']??0),(float)($student['english']??0),(float)($student['science']??0)],fn($v)=>$v>0);
$score=studentScore((float)($student['academic_average']??0),$academicAchievement,$organization,$nonAcademicAchievement,(float)($student['percentile']??100),$path,$subjects);
$indicatorLabels=['Linguistic'=>'Linguistik','Musical'=>'Musikal','Bodily'=>'Kinestetik','Logical-Mathematical'=>'Logis-Matematis','Spatial-Visualization'=>'Visual-Spasial','Interpersonal'=>'Interpersonal','Intrapersonal'=>'Intrapersonal','Naturalist'=>'Naturalis'];$canonicalIndicators=array_keys($indicatorLabels);
$indicatorAliases=['logical - mathematical'=>'Logical-Mathematical','logical mathematical'=>'Logical-Mathematical','spatial visualization'=>'Spatial-Visualization','natural'=>'Naturalist','naturalist'=>'Naturalist','nature'=>'Naturalist'];
$interestsQ=db()->prepare('SELECT indicator,score FROM interest_scores WHERE student_id=?');$interestsQ->execute([$studentId]);$interestInput=array_fill_keys($canonicalIndicators,0.0);foreach($interestsQ->fetchAll() as $interest){$indicator=trim((string)$interest['indicator']);$indicator=$indicatorAliases[strtolower($indicator)]??$indicator;if(isset($interestInput[$indicator]))$interestInput[$indicator]=max($interestInput[$indicator],(float)$interest['score']);}
$interests=[];foreach($canonicalIndicators as $indicator)$interests[$indicator]=['indicator'=>$indicator,'label'=>$indicatorLabels[$indicator],'score'=>$interestInput[$indicator]];$interests=array_values($interests);usort($interests,static function($a,$b)use($canonicalIndicators){$scoreOrder=$b['score']<=>$a['score'];return $scoreOrder!==0?$scoreOrder:array_search($a['indicator'],$canonicalIndicators,true)<=>array_search($b['indicator'],$canonicalIndicators,true);});$primary=$interests[0];$interestInput['Logical - Mathematical']=$interestInput['Logical-Mathematical'];
// Ensure score is numeric
foreach($interests as &$i){$i['score']=(float)$i['score'];}
$modelPrediction=null;$activeModel=db()->query("SELECT model_path FROM ml_models WHERE status='active' ORDER BY created_at DESC LIMIT 1")->fetchColumn();if($activeModel){try{$modelPrediction=Predictor::fromJson((string)$activeModel,['Linguistic'=>$interestInput['Linguistic']??0,'Musical'=>$interestInput['Musical']??0,'Bodily'=>$interestInput['Bodily']??0,'Logical - Mathematical'=>$interestInput['Logical - Mathematical'],'Spatial-Visualization'=>$interestInput['Spatial-Visualization']??0,'Interpersonal'=>$interestInput['Interpersonal']??0,'Intrapersonal'=>$interestInput['Intrapersonal']??0,'Naturalist'=>$interestInput['Naturalist']??0]);}catch(Throwable $e){}}
$predictedClass=(string)($modelPrediction['class']??$primary['indicator']);$passionIndicator=(string)$primary['indicator'];$potentialFits=MajorRecommendation::fromPrediction($predictedClass,$passionIndicator);$passionTerms=array_values(array_unique(array_merge($potentialFits,MajorRecommendation::competencyTerms($passionIndicator))));$passionFocus=MajorRecommendation::focus($passionIndicator);
$settings=getSchoolRankingWeights();
function csvCapacity(?string $value): ?int { $digits=preg_replace('/[^0-9]/','',(string)$value); return $digits===''?null:(int)$digits; }
function routeAverage(string $path,array $s): float {switch($path){case 'prestasi_akademik_sma':case 'prestasi_akademik_smk':return (float)($s['admission_prestasi_akademik']??$s['average_score']??0);case 'prestasi_non_akademik':return (float)($s['admission_prestasi_nonakademik']??$s['average_score']??0);case 'afirmasi_sma':return (float)($s['admission_afirmasi']??$s['average_score']??0);case 'zonasi_sma':return (float)($s['admission_zonasi']??$s['average_score']??0);case 'tahap_kedua_sma':return (float)($s['admission_tahap_kedua']??$s['average_score']??0);case 'afirmasi_tahap_kedua_smk':$a=(float)($s['admission_afirmasi']??0);$b=(float)($s['admission_tahap_kedua']??0);return $a&&$b?($a+$b)/2:($a?:($b?:($s['average_score']??0)));}return (float)($s['average_score']??0);}
function routeCapacity(string $path,array $s): ?int { $keys=['prestasi_akademik_sma'=>'capacity_prestasi_akademik','prestasi_akademik_smk'=>'capacity_prestasi_akademik','prestasi_non_akademik'=>'capacity_prestasi_nonakademik','afirmasi_sma'=>'capacity_afirmasi','zonasi_sma'=>'capacity_zonasi','tahap_kedua_sma'=>'capacity_tahap_kedua']; if($path==='afirmasi_tahap_kedua_smk'){ $a=$s['capacity_afirmasi']??null; $b=$s['capacity_tahap_kedua']??null; return $a !== null && $b !== null ? (int)round(((int)$a+(int)$b)/2) : ($a !== null ? (int)$a : ($b !== null ? (int)$b : null)); } $key=$keys[$path]??null; return $key!==null && ($s[$key]??null)!==null ? (int)$s[$key] : (($s['capacity']??null)!==null ? (int)$s['capacity'] : null); }
$schools=[];
try{$rows=db()->query('SELECT sd.*,GROUP_CONCAT(sc.competency SEPARATOR "||") competencies_text FROM school_data sd LEFT JOIN school_competencies sc ON sc.school_id=sd.id WHERE sd.is_active=1 GROUP BY sd.id ORDER BY sd.name')->fetchAll();foreach($rows as $r){$r['domisili']=$r['domicile'];$r['competencies']=array_values(array_filter(explode('||',(string)$r['competencies_text'])));$r['admission_average']=routeAverage($path,$r);$r['capacity']=routeCapacity($path,$r);$schools[]=$r;}}catch(Throwable $e){}
if(!$schools){
 $csv=__DIR__.'/../SMKSMA404.csv';if(is_readable($csv)&&($h=fopen($csv,'r'))){$headers=fgetcsv($h,0,';');while(($r=fgetcsv($h,0,';'))!==false){if(count($r)<20||trim((string)($r[0]??''))==='')continue;$capacityIndex=null;if(in_array($path,['prestasi_akademik_sma','prestasi_akademik_smk'],true))$capacityIndex=20;elseif($path==='prestasi_non_akademik')$capacityIndex=21;elseif($path==='tahap_kedua_sma')$capacityIndex=22;elseif($path==='afirmasi_sma')$capacityIndex=23;elseif($path==='zonasi_sma')$capacityIndex=24;$capacityValue=($capacityIndex!==null && isset($r[$capacityIndex]))?preg_replace('/[^0-9]/','',$r[$capacityIndex]):null;$schools[]=['npsn'=>$r[0],'name'=>$r[1],'address'=>$r[2],'domisili'=>$r[13],'school_type'=>stripos(trim($r[1]),'SMK')===0?'SMK':'SMA','average_score'=>(float)($r[14]??0),'capacity'=>$capacityValue!==null&&$capacityValue!==''?(int)$capacityValue:null,'capacity_prestasi_akademik'=>csvCapacity($r[20]??null),'capacity_prestasi_nonakademik'=>csvCapacity($r[21]??null),'capacity_tahap_kedua'=>csvCapacity($r[22]??null),'capacity_afirmasi'=>csvCapacity($r[23]??null),'capacity_zonasi'=>csvCapacity($r[24]??null),'accreditation'=>$r[19]??'','admission_prestasi_akademik'=>(float)($r[14]??0),'admission_prestasi_nonakademik'=>(float)($r[15]??0),'admission_tahap_kedua'=>(float)($r[16]??0),'admission_afirmasi'=>(float)($r[17]??0),'admission_zonasi'=>(float)($r[18]??0),'competencies'=>array_values(array_filter(array_slice($r,3,10),fn($v)=>trim((string)$v)!==''))];$schools[array_key_last($schools)]['admission_average']=routeAverage($path,$schools[array_key_last($schools)]);$schools[array_key_last($schools)]['capacity']=routeCapacity($path,$schools[array_key_last($schools)]);}fclose($h);}
}
$typeFilter=strtoupper(trim($_GET['type']??''));$domicileFilter=trim($_GET['domicile']??'');if($typeFilter!=='')$schools=array_values(array_filter($schools,fn($s)=>($s['school_type']??'')===$typeFilter));if($domicileFilter!=='')$schools=array_values(array_filter($schools,fn($s)=>strcasecmp((string)$s['domisili'],$domicileFilter)===0));
$ranked=RecommendationEngine::rank($schools,$student+['student_score'=>$score['total']],$passionTerms,$settings,$path);
$displaySchools=$ranked;
try{$save=db()->prepare('INSERT INTO recommendations(student_id,predicted_interest,confidence,student_score) VALUES(?,?,?,?)');$save->execute([$studentId,$predictedClass,$modelPrediction?(float)$modelPrediction['probability']:(float)$primary['score']/100,$score['total']]);}catch(Throwable $e){}
$partLabels=['academic'=>'Akademik','academic_achievement'=>'Prestasi Akademik','organization'=>'Organisasi','non_academic'=>'Prestasi Non-Akademik','percentile'=>'Persentil'];
$title='Rekomendasi sekolah';require __DIR__.'/../includes/header.php';
?>
<div class="container py-5">
<div class="result-hero mb-5"><div><div class="eyebrow mb-2">03 · Rekomendasi</div><h1 class="section-title mb-2">Bukan sekadar peringkat.<br><span class="accent-text">Ini peta pilihanmu.</span></h1></div><a href="<?=APP_URL?>/student/quiz.php" class="btn btn-outline-dark rounded-pill">Ulangi kuis minat</a></div>
<div class="row g-4 mb-4">
<div class="col-lg-5"><div class="passion-card"><div class="eyebrow">Fokus minat</div><h2><?=e($indicatorLabels[$predictedClass]??$predictedClass)?></h2><p><?=e($passionFocus['focus'])?></p><div class="passion-score"><?= $modelPrediction?round((float)$modelPrediction['probability']*100):round((float)$primary['score']) ?><small>% sinyal</small></div><div class="d-flex flex-wrap gap-2"><?php foreach(array_slice($potentialFits,0,8) as $fit):?><span class="fit-chip"><?=e($fit)?></span><?php endforeach;?></div><small>Kecocokan potensial diambil dari profesi yang muncul pada Dataset Project 404.</small></div></div>
<div class="col-lg-7"><div class="panel"><div class="d-flex justify-content-between align-items-center"><div><div class="eyebrow">Peta minat</div><h4 class="mb-0">8 kecenderungan utama</h4></div><span class="badge text-bg-light"><?=count($interests)?> indikator</span></div><canvas id="interestRadar" height="200"></canvas><div class="interest-list"><?php foreach($interests as $i):?><div class="interest-row"><span><?=e($i['label'])?></span><div class="progress-track"><span style="width:<?=$i['score']?>%"></span></div><strong><?=round((float)$i['score'])?>%</strong></div><?php endforeach;?></div></div></div>
</div>
<div class="row g-4 mb-5">
<div class="col-lg-8"><div class="panel"><div class="eyebrow">Formula Jalur Masuk (<?=e($routeLabel)?>)</div><h4 class="mt-1">Skor jalur: <?=number_format($score['total'],1)?> / 100</h4><p class="text-muted mb-3"><?=e($score['formula'])?></p><div class="formula-grid"><?php foreach($score['parts'] as $k=>$v):?><div><span><?=e($partLabels[$k]??ucwords(str_replace('_',' ',$k)))?></span><strong><?=number_format($v,1)?></strong></div><?php endforeach;?></div></div></div>
<div class="col-lg-4"><div class="panel"><div class="eyebrow">Metode rekomendasi</div><h4 class="mt-2">Pembobotan skor</h4><p class="small text-muted mb-2">Prioritas: Kesesuaian jurusan <?=round(($settings['major']??0.45)*100)?>% + Profil siswa <?=round(($settings['student']??0.30)*100)?>% + Kesesuaian rerata <?=round(($settings['average']??0.20)*100)?>% + Domisili <?=round(($settings['domicile']??0.05)*100)?>%</p><p class="small text-muted mb-0"><strong>Sangat sesuai:</strong> >=48% = kompetensi selaras dengan minat<br><strong>Sesuai terbatas:</strong> &lt;48% = kesesuaian terbatas</p></div></div>
</div>
<form class="panel mb-4" method="get"><div class="row g-2 align-items-end"><div class="col-md-4"><label class="form-label small">Jenjang</label><select class="form-select" name="type"><option value="">Semua yang eligible</option><option value="SMA" <?=$typeFilter==='SMA'?'selected':''?>>SMA</option><option value="SMK" <?=$typeFilter==='SMK'?'selected':''?>>SMK</option></select></div><div class="col-md-5"><label class="form-label small">Kota</label><select class="form-select" name="domicile"><option value="">Semua kota eligible</option><?php foreach(['Jakarta Pusat','Jakarta Barat','Jakarta Timur','Jakarta Selatan','Jakarta Utara','Kepulauan Seribu'] as $place):?><option <?=strcasecmp($domicileFilter,$place)===0?'selected':''?>><?=e($place)?></option><?php endforeach;?></select></div><div class="col-md-3"><button class="btn btn-dark rounded-pill w-100">Update matches</button></div></div></form>
<div class="d-flex justify-content-between align-items-end mb-3"><div><div class="eyebrow">Sekolah yang sesuai</div><h2 class="h3 mb-0"><?=count($displaySchools)?> sekolah paling relevan</h2></div><small class="text-muted">Program kompetensi ditampilkan lengkap</small></div>
<div class="row g-4"><?php if(!$displaySchools){ ?><div class="col-12"><div class="alert alert-warning">Belum ada sekolah eligible. Admin perlu melakukan import dataset atau melengkapi kompetensi sekolah.</div></div><?php } else { foreach($displaySchools as $i=>$s){ ?><div class="col-12"><article class="school-card school-card-pro"><div class="row g-4"><div class="col-lg-8"><div class="d-flex flex-wrap gap-2 align-items-center"><span class="rank-pill">#<?=($i+1)?></span><span class="badge text-bg-light"><?=e($s['school_type'])?></span><span class="badge <?=$s['major_match']>=48?'text-bg-success':'text-bg-warning'?>"><?=$s['major_match']>=48?'Passion match':'Limited match'?></span></div><h3 class="mt-3 mb-1"><a class="text-decoration-none text-reset" href="<?=APP_URL?>/student/school_detail.php?npsn=<?=urlencode($s['npsn'])?>"><?=e($s['name'])?></a></h3><p class="text-muted mb-2"><i class="bi bi-geo-alt"></i> <?=e($s['address'])?> · <?=e($s['domisili'])?></p><div class="d-flex flex-wrap gap-2"><?php foreach($s['competencies'] as $c):?><span class="competency-chip"><?=e(trim($c))?></span><?php endforeach;?></div></div><div class="col-lg-4"><div class="school-metrics"><div><span>Daya tampung</span><strong><?=$s['capacity']!==null?e((string)$s['capacity']):'Belum tersedia'?></strong></div><div><span>Akreditasi</span><strong><?=e((string)($s['accreditation']?:'Belum tersedia'))?></strong></div><div><span>Rerata jalur</span><strong><?=number_format((float)$s['admission_average'],2)?></strong></div><div><span>Match score</span><strong><?=e((string)$s['recommendation_score'])?>%</strong></div></div><p class="small text-muted mt-3 mb-0"><?=e($s['reasons'][0])?> · <?=e($s['reasons'][1])?></p></div></div></article></div><?php } } ?></div>
<p class="small text-muted mt-4">Daya tampung ditampilkan sesuai jalur masuk dari Dataset Project 404. Hasil bukan jaminan diterima.</p>
</div>
<script>const radar=document.getElementById('interestRadar');if(radar)new Chart(radar,{type:'radar',data:{labels:<?=json_encode(array_column($interests,'label'),JSON_UNESCAPED_UNICODE)?>,datasets:[{data:<?=json_encode(array_map('floatval',array_column($interests,'score')))?>}]},options:{plugins:{legend:{display:false}},scales:{r:{min:0,max:100,ticks:{display:false}}}}});</script>
<?php require __DIR__.'/../includes/footer.php';?>
