<?php
declare(strict_types=1);
require_once __DIR__.'/../config/database.php';require_login();if((current_user()['role']??'')!=='admin')redirect('dashboard.php');
$message='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'&&verify_csrf($_POST['csrf']??null)){try{$a=$_POST['action']??'';if($a==='save'){db()->prepare('INSERT INTO majors(name,explanation,priority) VALUES(?,?,?) ON DUPLICATE KEY UPDATE explanation=VALUES(explanation),priority=VALUES(priority),is_active=1')->execute([trim($_POST['name']),trim($_POST['explanation']), (int)$_POST['priority']]);$message='Pathway disimpan.';}elseif($a==='delete'){db()->prepare('UPDATE majors SET is_active=0 WHERE id=?')->execute([(int)$_POST['id']]);$message='Pathway dinonaktifkan.';}}catch(Throwable $e){$error=$e->getMessage();}}
$majors=db()->query('SELECT * FROM majors WHERE is_active=1 ORDER BY priority DESC,name')->fetchAll();$title='Pathway management';require __DIR__.'/../includes/header.php';
?>
<div class="container py-5"><div class="admin-hero mb-4"><div><div class="eyebrow">Admin · pathway architecture</div><h1 class="section-title mb-2">Pathways yang nyambung ke passion.</h1><p class="text-muted mb-0">Kelola nama kompetensi, penjelasan, prioritas, dan gunakan alias untuk memperkuat matching sekolah.</p></div><div class="admin-hero-mark"><i class="bi bi-signpost-split"></i></div></div>
<?php if($message):?><div class="alert alert-success"><?=e($message)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?>
<div class="row g-4"><div class="col-lg-5"><form method="post" class="panel"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save"><div class="eyebrow">CRUD</div><h4 class="mt-2">Create / update pathway</h4><label class="form-label mt-3">Pathway name</label><input class="form-control mb-3" name="name" required><label class="form-label">Explanation</label><textarea class="form-control mb-3" name="explanation" rows="4"></textarea><label class="form-label">Priority</label><input class="form-control mb-3" type="number" name="priority" value="0"><button class="btn btn-accent rounded-pill">Save pathway</button></form></div><div class="col-lg-7"><div class="panel"><div class="d-flex justify-content-between mb-3"><div><div class="eyebrow">Active pathways</div><h4 class="mb-0"><?=count($majors)?> pathways</h4></div></div><?php foreach($majors as $m):?><div class="admin-list-row"><div><strong><?=e($m['name'])?></strong><p class="small text-muted mb-0"><?=e($m['explanation']??'')?></p></div><div class="d-flex gap-2 align-items-center"><span class="badge text-bg-light">P<?=$m['priority']?></span><form method="post" onsubmit="return confirm('Nonaktifkan pathway ini?')"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$m['id']?>"><button class="btn btn-sm btn-outline-danger rounded-pill">Delete</button></form></div></div><?php endforeach;?></div></div></div></div>
<?php require __DIR__.'/../includes/footer.php';?>
