<?php
declare(strict_types=1);
require_once __DIR__.'/../config/database.php';require_login();if((current_user()['role']??'')!=='admin')redirect('dashboard.php');
$inds=['Linguistic','Musical','Bodily','Logical-Mathematical','Spatial-Visualization','Interpersonal','Intrapersonal','Naturalist'];$message='';
if($_SERVER['REQUEST_METHOD']==='POST'&&verify_csrf($_POST['csrf']??null)){try{$a=$_POST['action']??'add';if($a==='add'&&trim($_POST['question']??'')!==''){db()->prepare('INSERT INTO quiz_questions(question,indicator,weight,order_number) VALUES(?,?,?,?)')->execute([trim($_POST['question']),$_POST['indicator'],(float)$_POST['weight'],(int)$_POST['order_number']]);$message='Question ditambahkan.';}elseif($a==='delete'){db()->prepare('UPDATE quiz_questions SET is_active=0 WHERE id=?')->execute([(int)$_POST['id']]);$message='Question dinonaktifkan.';}}catch(Throwable $e){$message=$e->getMessage();}}
$questions=db()->query('SELECT * FROM quiz_questions WHERE is_active=1 ORDER BY order_number,id')->fetchAll();$title='Quiz management';require __DIR__.'/../includes/header.php';
?>
<div class="container py-5"><div class="admin-hero mb-4"><div><div class="eyebrow">Admin · passion quiz</div><h1 class="section-title mb-2">Pertanyaan yang lebih tajam.</h1><p class="text-muted mb-0">Atur indikator, bobot, urutan, dan aktif/nonaktifkan pertanyaan.</p></div><div class="admin-hero-mark"><i class="bi bi-ui-checks-grid"></i></div></div>
<?php if($message):?><div class="alert alert-info"><?=e($message)?></div><?php endif;?><div class="row g-4"><div class="col-lg-5"><form method="post" class="panel"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="add"><label class="form-label">Question</label><textarea class="form-control mb-3" name="question" required></textarea><label class="form-label">Indicator</label><select class="form-select mb-3" name="indicator"><?php foreach($inds as $i):?><option><?=$i?></option><?php endforeach;?></select><div class="row"><div class="col-6"><label class="form-label">Weight</label><input class="form-control" type="number" step=".1" name="weight" value="1"></div><div class="col-6"><label class="form-label">Order</label><input class="form-control" type="number" name="order_number" value="<?=count($questions)+1?>"></div></div><button class="btn btn-accent rounded-pill mt-4">Add question</button></form></div><div class="col-lg-7"><div class="panel table-responsive"><table class="table align-middle"><thead><tr><th>#</th><th>Question</th><th>Indicator</th><th></th></tr></thead><tbody><?php foreach($questions as $q):?><tr><td><?=$q['order_number']?></td><td><?=e($q['question'])?></td><td><span class="badge text-bg-light"><?=e($q['indicator'])?></span></td><td><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$q['id']?>"><button class="btn btn-sm btn-outline-danger rounded-pill">Delete</button></form></td></tr><?php endforeach;?></tbody></table></div></div></div></div>
<?php require __DIR__.'/../includes/footer.php';?>
